### PR TITLE
Add Riviera DEV 2018

### PR DESCRIPTION
**Pull request by Jean-Michael**
Add Riviera DEV 2018

### CODE REVIEW

**Comment by lucj** [comment]
Thanks Jean-Michel. I've changed the way it's handled so it's a little bit more dynamic. I'll add Riviera Dev in the events.json file

**Comment by Jean-Michael** [comment]
Thank you Luc.
I closed the PR by mistake, I just reopened it to allow you to make the changes

Regards,
Jean-Michael

**Comment by lucj** [comment]
Hi, 
I have added RivieraDev in the events.json but I still have some funky looking in the image rendering.
I need to change that so image correctly fit in the item header.
I close the PR then, is that fine ?

**Comment by lucj** [comment]
Do you have a rivieradev png 600*150 with transparent background ?

**Comment by Jean-Michael** [comment]
Hi Luc,

I have added a PNG 600*196 with transparent background.
600*196 keeps a better ratio than 600*150.
Is that fine ?

Rgds,
Jean-Michael

**Comment by lucj** [comment]
Hi Jean-Michel, great one, thanks.

**Comment by lucj** [comment]
Closing this one as item has been added.
Thanks for the assets @Jean-Michael

**Pull request closed without merging**
